### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [flowlo/gothon#1]
First of all, thanks for sharing a great software!

Could you add LICENSE file?
The following page may help for choosing a license.
[Choose an open source license - Choose a License](http://choosealicense.com/)

I hope you choose a permissive license like MIT or Apache license.
Thanks!

**Comment by lorenzleutgeb** [comment]
Sure, I am a fan of the Apache license, it will be there in a jiffy.

**Comment by hnakamur** [comment]
Thanks!
